src/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.urlresolvers import reverse
import sys
import os

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Index page
	url(r'^$', RedirectView.as_view(pattern_name='task_list', permanent=True), name="index"),
	
	# Admin
	url(r'^admin/tasks/task/(?P<task_id>\d+)/model_solution', 'tasks.views.model_solution', name="model_solution"),
	url(r'^admin/tasks/task/(?P<task_id>\d+)/final_solutions', 'tasks.views.download_final_solutions', name="download_final_solutions"),
	url(r'^admin/attestation/ratingscale/generate', 'attestation.views.generate_ratingscale', name="generate_ratingscale"),
	(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    
	# Login and Registration
	(r'^accounts/', include('accounts.urls')),
	
	# tinyMCE 
	(r'^tinymce/', include('tinymce.urls')),
					   
	#Tasks
	url(r'^tasks/$', 'tasks.views.taskList', name = 'task_list'),
	url(r'^tasks/(?P<task_id>\d+)/$', 'tasks.views.taskDetail', name='task_detail'),

	# Solutions
	url(r'^solutions/(?P<solution_id>\d+)/$', 'solutions.views.solution_detail', name='solution_detail',kwargs={'full' : False}),
    url(r'^solutions/(?P<solution_id>\d+)/full/$', 'solutions.views.solution_detail', name='solution_detail_full', kwargs={'full': True}),
	url(r'^solutions/(?P<solution_id>\d+)/download$', 'solutions.views.solution_download', name='solution_download',kwargs={'full' : False}),
   	url(r'^solutions/(?P<solution_id>\d+)/download/(?P<full>full)/$', 'solutions.views.solution_download', name='solution_download'),
	url(r'^solutions/(?P<solution_id>\d+)/run_checker$', 'solutions.views.solution_run_checker', name='solution_run_checker'),
	url(r'^tasks/(?P<task_id>\d+)/checkerresults/$', 'solutions.views.checker_result_list', name='checker_result_list'),
	url(r'^tasks/(?P<task_id>\d+)/solutiondownload$', 'solutions.views.solution_download_for_task', name='solution_download_for_task',kwargs={'full' : False}),
	url(r'^tasks/(?P<task_id>\d+)/solutiondownload/(?P<full>full)/$', 'solutions.views.solution_download_for_task', name='solution_download_for_task'),
	url(r'^tasks/(?P<task_id>\d+)/solutionupload/$', 'solutions.views.solution_list', name='solution_list'),
	url(r'^tasks/(?P<task_id>\d+)/solutionupload/user/(?P<user_id>\d+)$', 'solutions.views.solution_list', name='solution_list'),
	url(r'^tasks/(?P<task_id>\d+)/solutionupload/test/$', 'solutions.views.test_upload', name='upload_test_solution'),
	url(r'^tasks/(?P<task_id>\d+)/solutionupload/test/student/$', 'solutions.views.test_upload_student', name='upload_test_solution_student'),

	url(r'^tasks/(?P<task_id>\d+)/jplag$', 'solutions.views.jplag', name='solution_jplag'),

	#Attestation
	url(r'^tasks/(?P<task_id>\d+)/attestation/statistics$', 'attestation.views.statistics', name='statistics'),
	url(r'^tasks/(?P<task_id>\d+)/attestation/$', 'attestation.views.attestation_list', name='attestation_list'),
	url(r'^tasks/(?P<task_id>\d+)/attestation/new$', 'attestation.views.new_attestation_for_task', name='new_attestation_for_task'),
	url(r'^solutions/(?P<solution_id>\d+)/attestation/new$', 'attestation.views.new_attestation_for_solution', name='new_attestation_for_solution', kwargs={'force_create' : False}),
	url(r'^solutions/(?P<solution_id>\d+)/attestation/new/(?P<force_create>force_create)$', 'attestation.views.new_attestation_for_solution', name='new_attestation_for_solution'),
	url(r'^attestation/(?P<attestation_id>\d+)/edit$', 'attestation.views.edit_attestation', name='edit_attestation'),
	url(r'^attestation/(?P<attestation_id>\d+)/withdraw$', 'attestation.views.withdraw_attestation', name='withdraw_attestation'),
	url(r'^attestation/(?P<attestation_id>\d+)/run_checker', 'attestation.views.attestation_run_checker', name='attestation_run_checker'),
	url(r'^attestation/(?P<attestation_id>\d+)$', 'attestation.views.view_attestation', name='view_attestation'),
	url(r'^attestation/rating_overview$', 'attestation.views.rating_overview', name='rating_overview'),
	url(r'^attestation/rating_export.csv$', 'attestation.views.rating_export', name='rating_export'),
	
	url(r'^tutorial/$', 'attestation.views.tutorial_overview', name='tutorial_overview'),
   	url(r'^tutorial/(?P<tutorial_id>\d+)$', 'attestation.views.tutorial_overview', name='tutorial_overview'),
	
	# Uploaded media
	url(r'^upload/(?P<path>SolutionArchive/Task_\d+/User_.*/Solution_(?P<solution_id>\d+)/.*)$', 'utilities.views.serve_solution_file'),
	url(r'^upload/(?P<path>TaskMediaFiles.*)$', 'utilities.views.serve_unrestricted'),
	url(r'^upload/(?P<path>jplag.*)$', 'utilities.views.serve_staff_only', name='jplag_download'),
	url(r'^upload/(?P<path>CheckerFiles.*)$', 'utilities.views.serve_staff_only'),
	url(r'^upload/(?P<path>.*)$', 'utilities.views.serve_access_denied'),
	
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

src/attestation/models.py
from django.db import models
from django.conf import settings
from tasks.models import Task
from solutions.models import Solution, SolutionFile
from django.utils.translation import ugettext_lazy as _
from django.core.mail import EmailMessage
from django.template import Context, loader
from django.contrib.sites.requests import RequestSite
from datetime import datetime
from utilities.nub import nub
import difflib

from accounts.models import User
from configuration import get_settings


class Attestation(models.Model):
	""""""

	created = models.DateTimeField(auto_now_add=True)
	solution = models.ForeignKey(Solution)
	author = models.ForeignKey(User, verbose_name="attestation author", limit_choices_to = {'groups__name': 'Tutor'})

	public_comment = models.TextField(blank=True, help_text = _('Comment which is shown to the user.'))
	private_comment = models.TextField(blank=True, help_text = _('Comment which is only visible to tutors'))
	final_grade = models.ForeignKey('RatingScaleItem', null=True, help_text = _('The mark for the whole solution.'))
	
	final = models.BooleanField(default = False, help_text = _('Indicates whether the attestation is ready to be published'))
	published = models.BooleanField(default = False, help_text = _('Indicates whether the user can see the attestation.'))
	published_on = models.DateTimeField(blank=True,null=True,help_text = _('The Date/Time the attestation was published.'))
	
	def publish(self, request, by):
		""" Set attestation to published and send email to user """
		self.published = True
		self.published_on = datetime.now()
		self.save()

                email = self.solution.author.email
                if not email:
                    return

		# Send confirmation email
                t = loader.get_template('attestation/attestation_email.html')
                c = {
                        'attest': self,
                        'protocol': request.is_secure() and "https" or "http",
                        'domain': RequestSite(request).domain,
                        'site_name': settings.SITE_NAME,
                        'by': by,
                        'invisible_attestor' : get_settings().invisible_attestor,
                        }
                subject = _("New attestation for your solution of the task '%s'") % self.solution.task
                body = t.render(Context(c))
                reply_to = ([self.author.email]                    if self.author.email and (not get_settings().invisible_attestor) else []) \
                         + ([get_settings().attestation_reply_to]  if get_settings().attestation_reply_to else [])
                headers = {'Reply-To': ', '.join(reply_to)} if reply_to else None
                email = EmailMessage(subject, body, None, (email,), headers = headers)
                email.send()

        def withdraw(self, request, by):
		self.published = False
                self.final = False
		self.published_on = datetime.now()
		self.save()

                recps = nub([
                    self.solution.author, # student
                    self.author,          # attestation writer
                    by,                   # usually attestation writer, may be trainer
                    ] + list(User.objects.filter(groups__name="Trainer"))  # and, for withdrawals, all trainers
                    )
                emails = [u.email for u in recps if u.email]

                if not emails:
                    return

		# Send confirmation email
                t = loader.get_template('attestation/attestation_withdraw_email.html')
                c = {
                        'attest': self,
                        'protocol': request.is_secure() and "https" or "http",
                        'domain': RequestSite(request).domain,
                        'site_name': settings.SITE_NAME,
                        'by': by,
                        }
                subject = _("Attestation for your solution of the task '%s' withdrawn") % self.solution.task
                body = t.render(Context(c))
                recipients = emails[0:1]
                bcc_recipients = emails[1:]
                email = EmailMessage(subject, body, None, recipients, bcc_recipients)
                email.send()

class AnnotatedSolutionFile(models.Model):
	""""""
	attestation = models.ForeignKey(Attestation)
	solution_file = models.ForeignKey(SolutionFile)
	content = models.TextField(help_text = _('The content of the solution file annotated by the tutor.'), blank = True)
	
	def has_anotations(self):
		original = self.solution_file.content().replace("\r\n","\n").replace("\r","\n")
		anotated = self.content.replace("\r\n","\n").replace("\r","\n")
		return not original == anotated
	
	def content_diff(self):
		d = difflib.Differ()
		original = self.solution_file.content().replace("\r\n","\n").replace("\r","\n").splitlines(0)
		anotated = self.content.replace("\r\n","\n").replace("\r","\n").splitlines(0)
		result = list(d.compare(original, anotated))
		return "\n".join(map(lambda l: l.strip("\n"), result))
	
	def __unicode__(self):
		return self.solution_file.__unicode__()
	
class RatingAspect(models.Model):
	""" describes an review aspect which the reviewer has to evaluate """	
	name = models.CharField(max_length=100, help_text = _('The Name of the Aspect to be rated. E.g.: "Readabylity"'))
	description = models.TextField(help_text = _('Description of the Aspect and how it should be rated. E.w.: "How well is the code structured?"'))
	
	def __unicode__(self):
		return self.name

class RatingScale(models.Model):
	""" describes a scale upone which the reviewer rates the aspect """
	name = models.CharField(max_length=100, help_text = _('The Name of the rating scale for the aspects. E.g.: "School marks"'))
	
	def __unicode__(self):
		return self.name
	
class RatingScaleItem(models.Model):
	""" lists all items(marks) of an rating scale"""	
	scale = models.ForeignKey(RatingScale)
	name = models.CharField(max_length=100, help_text = _('The Name of the item(mark) in the rating scale. E.g.: "A" or "very good" '))
	position = models.PositiveSmallIntegerField(help_text = _('Defines the order in which the items are sorted. Lowest is best.'))
	
	class Meta:
		ordering = ['position']
	
	def __unicode__(self):
		return self.name

class Rating(models.Model):
	""" intermediate model to assign a rating aspect and a rating scale to a task """
	task = models.ForeignKey(Task)
	aspect = models.ForeignKey(RatingAspect)
	scale = models.ForeignKey(RatingScale)
	
	def __unicode__(self):
		return "%s - %s - %s" % (self.task.title, self.aspect.name, self.scale.name)
		
class RatingResult(models.Model):
	""" the rating of particular aspect of a specific solution """
	attestation = models.ForeignKey(Attestation)
	rating = models.ForeignKey(Rating)
	mark = models.ForeignKey(RatingScaleItem, null=True) # allow for db-null so that rating results can be created programaticly without mark (blank = False !)

	def __unicode__(self):
		return unicode(self.rating.aspect) 
	
class Script(models.Model):
	""" save java script function of the rating overview page """
	script = models.TextField(blank=True, help_text = _("This JavaScript will calculate a recommend end note for every user based on final grade of every task."), default="""var sum = 0.0;\nfor (x = 0; x != grades.length; ++x) {\n    grade = parseFloat(grades[x]);\n    if (!isNaN(grade)) {\n        sum += grade;\n    }\n}\nresult=sum;""")
	
	

src/attestation/forms.py
# -*- coding: utf-8 -*-

from django.utils.translation import ugettext_lazy as _
from django.forms.models import ModelForm, inlineformset_factory, BaseInlineFormSet
from django.forms.formsets import formset_factory
from django import forms

from attestation.models import Attestation, AnnotatedSolutionFile, RatingResult, Script,SolutionFile
from configuration.models import Settings
											

class AttestationForm(ModelForm):
	class Meta:
		model = Attestation
		exclude = ('solution', 'author', 'final', 'published','published_on')
		widgets = {
			'public_comment': forms.Textarea(attrs={'cols': 80, 'rows': 10}),
			'private_comment': forms.Textarea(attrs={'cols': 80, 'rows': 10}),
		}

		
	def __init__(self, *args, **kwargs): 
		super(AttestationForm, self).__init__(*args, **kwargs) 
		final_grade_rating_scale = kwargs['instance'].solution.task.final_grade_rating_scale
		if final_grade_rating_scale:
			self.fields['final_grade'].choices = [ (item['id'], item['name']) for item in final_grade_rating_scale.ratingscaleitem_set.values() ]
		else:
			del self.fields['final_grade']
	
class AttestationPreviewForm(ModelForm):
	class Meta:
		model = Attestation
		fields = ('final',)

class AnnotatedFileForm(ModelForm):
	class Meta:
		model = AnnotatedSolutionFile
		fields=('content','solution_file',)

	solution_file = forms.IntegerField(widget=forms.HiddenInput)

	def clean_solution_file(self):
		solution_file_id = self.cleaned_data.get('solution_file')
		try:
			solution_file  = SolutionFile.objects.get(pk=solution_file_id)
		except SolutionFile.DoesNotExist:
			raise forms.ValidationError("No Solutionfile exists by id"+solution_file_id)

		return solution_file


		
AnnotatedFileFormSet = inlineformset_factory(Attestation, AnnotatedSolutionFile, form=AnnotatedFileForm, formset=BaseInlineFormSet, can_delete=False, extra=0)


class RatingResultForm(ModelForm):
	def __init__(self, *args, **kwargs): 
		super(RatingResultForm, self).__init__(*args, **kwargs)
		ratingResult = kwargs['instance']
		self.fields['mark'].label = ratingResult.rating.aspect.name 
		self.fields['mark'].help_text = ratingResult.rating.aspect.description 
		self.fields['mark'].choices = [ (item['id'], item['name']) for item in ratingResult.rating.scale.ratingscaleitem_set.values() ]
	
	class Meta:
		model = RatingResult
		fields=('mark',)

RatingResultFormSet = inlineformset_factory(Attestation, RatingResult, form=RatingResultForm, formset=BaseInlineFormSet, can_delete=False, extra=0)

class ScriptForm(ModelForm):
	class Meta:
		model = Script
                fields = '__all__'

class PublishFinalGradeForm(ModelForm):
	class Meta:
		model = Settings
		fields = ('final_grades_published',)

class GenerateRatingScaleForm(forms.Form):
	name = forms.CharField(max_length=200,  help_text = 'The Name of the rating scale for the aspects. E.g.: "School marks"')
	start = forms.FloatField(initial=0, help_text="The first RatingScaleItem to generate.")
	end = forms.FloatField(initial=15, help_text="The last RatingScaleItem to generate.")
	step = forms.FloatField(initial=1, help_text="The step size between the RatingScaleItems.")

src/templates/attestation/attestation_view.html
{% extends "base.html" %}
{% load highlight %}{% load i18n  %}
{% block extrahead %}{{ block.super }}
	<script type="text/javascript" src="{{STATIC_URL}}/frameworks/jquery.easy-confirm-dialog/jquery.easy-confirm-dialog.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}script/solution_inlines.js"></script>
	<link type="text/css" rel="stylesheet" href="{{STATIC_URL}}styles/pygments_friendly.css" />
	<script type="text/javascript">	
		function updatePublishButton(){
			if ($('#id_final').is(':checked')) {
				$('#publishButton').removeAttr('disabled');
			} else {
				$('#publishButton').attr('disabled', true);
			} 
		}
		$(document).ready(function(){
			updatePublishButton();
			$('#id_final').click(function(){updatePublishButton()});

			$(".withdraw").easyconfirm({
				locale: {
					title: 'Are you sure?',
					text: 'Really withdraw this attestion? The student and the trainers will be notified by e-mail.',
					button: ['Cancel','Withdraw'],
					closeText: 'Cancel',
					},
				eventType:
					'submit'
			});
		});

	</script>
{% endblock %}
{% block breadcrumbs %} {{block.super}} > <a href={% url "task_detail" task_id=attest.solution.task.id%}>{{attest.solution.task.title}}</a> 
{% if user.is_tutor %}
	> <a href={% url "attestation_list" attest.solution.task_id %}>My attestations</a> 
	> <a href={% url "edit_attestation" attest.id %}>Attestation</a>
	> Preview
{% else %}
	> <a href={% url "solution_list" task_id=attest.solution.task.id%}>My solutions</a> 
	> <a href={% url "solution_detail" solution_id=attest.solution.id%}>Solution {{attest.solution.id}}</a> 
	> Attestation {{attest.id}}
{% endif %}
{% endblock %}
{% block content %}<div id='attestation_view'>

<h1>{% trans "Attestation"%}: {{attest.solution.task.title}}</h1>
<p id='author'>{% if show_attestor %}by {{attest.author.get_full_name}}{% endif %} {% if show_author or user.is_trainer or attest.published %} for {{attest.solution.author}} {% endif %}</p>

{% if attest.private_comment %}
	{% if user.is_trainer or user.is_tutor %}
		<div class="section private">
			<h2>Private Comment</h2>
			<p>{{attest.private_comment}}</p>	
		</div>
	{% endif %}
{% endif %}

{% if attest.public_comment %}
	<div class="section">
		<h2>Comment</h2>
		<p>{{attest.public_comment|linebreaks}}</p>	
	</div>
{% endif %}

{% if attest.final_grade or attest.ratingresult_set.all %}
	<div class="section">
		<h2>Ratings</h2>
		{% for ratingresult in attest.ratingresult_set.all%}
			<div class="result">
				<h3 href="#">{{ratingresult.rating.aspect.name}}: <span class="mark">{{ratingresult.mark}}</h3>
				<p>{{ratingresult.aspect.description}}</p>
			</div>
		{%endfor%}
		{% if attest.final_grade %} 
			<div class="result">
				<h3 href="#">Final grade: <span class="mark">{{attest.final_grade}}</h3>
			</div>
		{% endif %}
	</div>
{% endif %}


{% if user.is_trainer or user.is_tutor %}
	<div class="section private">
		<h2>Checker results</h2>
		{% with attest.solution.allCheckerResults as results %}
			{% include "solutions/checker_results_inline.html" %}
		{% endwith %}
	</div>
{% endif %}

<a href={% url "solution_download" solution_id=attest.solution.id %} id='download'><span class="ui-icon ui-icon-disk"></span>Download Solution</a>
<h2>{% trans "Annotated Files" %}</h2>
<div class="filetabs">
	<ul>
		{% for anotfile in attest.annotatedsolutionfile_set.all%}
			<li><a href="#file{{forloop.counter}}">{{anotfile}}{% if anotfile.has_anotations%}<span class="has_anotations">*</span>{% endif %}</a></li> 
		{%endfor%} 
	</ul> 	

	{% for anotfile in attest.annotatedsolutionfile_set.all%}
		<div class="file" id="file{{forloop.counter}}">
			<h3>{{solutionfile}}</h3>
			<div class="content">{{anotfile.content_diff|highlight_table:anotfile.solution_file.file.name|highlight_diff}}</div>
		</div>
	{%endfor%}
</div>

{% if submitable %}
	<br/><br/>
	<form method="post">{% csrf_token %}
		{% include "forms/form_as_div.html" %}
		<input type="submit" name="save" value="Save" />
        {% if not attest.solution.task.only_trainers_publish %}
		<input id="publishButton" type="submit" name="publish" value="Save and publish" />
        {% endif %}
		<input type="button" value="Edit again" onClick="parent.location='{% url "edit_attestation" attest.id %}'">
	</form>
{% endif %}

{% if withdrawable %}
    {% if not attest.solution.task.only_trainers_publish %}
        <br/><br/>
        <form method="post" class="withdraw" action="{% url "withdraw_attestation" attest.id %}">{% csrf_token %}
            <input type="submit" name="withdraw" value="Withdraw published attestation" />
        </form>
    {% endif %}
{% endif %}

{% endblock %}

src/templates/attestation/attestation_withdraw_email.html
{% load i18n %}{% autoescape off %}{% trans "Hello " %}{{attest.solution.author}},
{% with attest.solution.task as task %}
{% blocktrans %}the attestation of your solution to the task "{{task}}" has been withdrawn by {{by}}.{% endblocktrans %}{% endwith%}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

src/templates/attestation/rating_overview.html
{% extends "base.html" %}
{% load highlight %} {% load i18n  %}
{% block extrahead %}{{ block.super }}
<script src="{{STATIC_URL}}frameworks/ace/src-min/ace.js" type="text/javascript" charset="utf-8"></script>
<script src="{{STATIC_URL}}frameworks/ace/src-min/theme-twilight.js" type="text/javascript" charset="utf-8"></script>
<script src="{{STATIC_URL}}frameworks/ace/src-min/mode-javascript.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">	
	
	
	var editor;
	window.onload = function() {
		$("#editor").html($("#id_script").text())
		$("#id_script").hide()
		editor = ace.edit("editor");
		editor.setTheme("ace/theme/twilight");
		editor.renderer.setShowPrintMargin(false);
		var JavaScriptMode = require("ace/mode/javascript").Mode;
		editor.getSession().setMode(new JavaScriptMode());
		calculate();
		$(".calculated_grade_cell").hover(
										  function () {
										  $(this).append($("<span class='icon ui-icon-arrowreturnthick-1-e'></span>"));
										  }, 
										  function () {
										  $(this).find("span:last").remove();
										  }
										  );
		$(".calculated_grade_cell").click(function () {
										  $(this).next().find("input[type=text]")[0].value = $(this).text();
										  });
		$("input[type=submit]").click(function () {
									  $("#id_script").text(editor.getSession().getValue());
									  })
		
	};	
	
	
	function calculate(){
		var all_grades = new Array();
		var all_plagiarism = new Array();
		var all_aspects = new Array();
		$('.user_row').each(function(index) {
							var grades=new Array();
							var plagiarism=new Array();
							var aspects=new Array();
							var result;
							$(this).find('.grade_cell').each(function(index) {
								grades[index] = $(this).data('score');
								plagiarism[index] = $(this).data('plagiarism') == 'yes';
								aspects[index] = new Object();
								$(this).find('.aspect_span').each(function(index_unused) {
									aspects[index][$(this).data('aspect')] = $(this).data('score');
								});
							});
							all_grades[index] = grades;
							all_plagiarism[index] = plagiarism;
							all_aspects[index] = aspects;
							});
	
		
		{% include "attestation/rating_scale_items_js_inline.html" %}
		
		for (index in all_grades){
			var grades = all_grades[index];
			var plagiarism = all_plagiarism[index];
			var aspects = all_aspects[index];
			var result;
			
			try {
				eval(editor.getSession().getValue());
			} catch (e) {
			}
			
			$("#calculated_grade_cell"+index).text(result);
		}
	}
	
	function takeAll(){
		$(".calculated_grade_cell").click();
	}
	
</script>
{% endblock %} 
{% block breadcrumbs %} {{block.super}} > Rating Overview {% endblock %}
{% block content %}<div id="rating">
<h2>{% trans "Rating Overview" %}</h2>



<div><form method="post" action="">{% csrf_token %}

	<pre id="editor"></pre>
	
	{{script_form.script}}
	<input type="button" id="calculate_button" value="calculate" onClick="calculate()" />
	<p class="help">
		This JavaScript will be executed for every user listed below to calculate a proposed end note.
		This calculation is also shown to the tutors and users.
		<i><b>grades</b></i> is an Array containing all final grades for one user as Stings.
		<i><b>plagiarism</b></i> is an Array of booleans, indicating whether the solution was plagiarism.
		<i><b>ratingScaleItems</b></i> is an array of arrays containing the names of the rating scale items of every task's final grade rating scale.
		<i><b>aspects</b></i> is a map from additional rating aspects (if any are present, identified by their name) to their value.
		Save the end note recommendation in <i><b>result</b></i> so it can be displayed in the row 'Calculated grade' and on the user index page.
</p>

	<div id="email"><a href="mailto:?bcc={% for user, attestations in rating_list %}{{user.email}},{% endfor %}"><span class="icon ui-icon-mail-closed"></span>Email all users</a></div>  <div id="export"><a href="{% url "rating_export" %}"><span class="icon ui-icon-extlink"></span>Export as csv (utf-8)</a></div>

    {{ final_grade_formset.management_form }}
	<table class="noLinkHighlight">
		<tr>
			<th>User</th>
			{% for task in tasks %}
				<th><div class="heading"><a href="{% url "task_detail" task_id=task.id  %}">{{task.title}}</a></div></th>
			{% endfor %}
			<th><div class="heading" id="calculated_grade_heading">Calculated grade</div></th>
			<th>Final grade</th>
		</tr>
		{% for user, attestations in rating_list %}
			<tr class="{% cycle 'odd' 'even' %} user_row">
				<td><a href="mailto:{{user.email}}">{{user.get_full_name}}</a></td>
				{% for attestation in attestations %}
				    {% if attestation.solution.plagiarism %}
							<td class="grade_cell" data-plagiarism="yes"><span class="icon ui-icon-alert icon-red" title="Marked as plagiarism"></span></td>
						{% else %}
						{% if attestation.final_grade %}
							<td class="grade_cell" data-score="{{attestation.final_grade}}">
							{% for ratingresult in attestation.ratingresult_set.all %}
								<span class="aspect_span" data-aspect="{{ratingresult.rating.aspect.name}}" data-score="{{ratingresult.mark.name}}"></span>
							{% endfor %}
							<span title="{% for ratingresult in attestation.ratingresult_set.all %}{{ratingresult.rating.aspect.name}}: {{ratingresult.mark.name}},{% endfor %}">
							  <a href="{% url "view_attestation" attestation_id=attestation.id%}">{{attestation.final_grade}}</a>
							</span>
							</td>
						{% else %}
							<td class="grade_cell">-</td>
						{% endif %}
						{% endif %}
	
				{% endfor %}
				<td class="calculated_grade_cell" id="calculated_grade_cell{{forloop.counter0}}"></td>
				<td>
					{% with final_grade_formset.forms.pop as form %}
						{% for field in form.hidden_fields %} {{field}} {% endfor %}
						{{ form.final_grade }}
					{% endwith %}
				</td>
			</tr>
		{% endfor %}
		<tr>
			<td></td>{% for task in tasks %}<td></td>{% endfor %}<td><a onClick="takeAll()">take all<span class='icon ui-icon-arrowreturnthick-1-e'></span></a></td><td></td>
		</tr>
	</table>
	{{publish_final_grade_form}}
	<input type="submit" name="submit" value="Save Grades and Script" />
</form></div>
</div>
{% endblock %}