src/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.urlresolvers import reverse
import sys
import os

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Index page
	url(r'^$', RedirectView.as_view(pattern_name='task_list', permanent=True), name="index"),
	
	# Admin
	url(r'^admin/tasks/task/(?P<task_id>\d+)/model_solution', 'tasks.views.model_solution', name="model_solution"),
	url(r'^admin/tasks/task/(?P<task_id>\d+)/final_solutions', 'tasks.views.download_final_solutions', name="download_final_solutions"),
	url(r'^admin/attestation/ratingscale/generate', 'attestation.views.generate_ratingscale', name="generate_ratingscale"),
	(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    
	# Login and Registration
	(r'^accounts/', include('accounts.urls')),
	
	# tinyMCE 
	(r'^tinymce/', include('tinymce.urls')),
					   
	#Tasks
	url(r'^tasks/$', 'tasks.views.taskList', name = 'task_list'),
	url(r'^tasks/(?P<task_id>\d+)/$', 'tasks.views.taskDetail', name='task_detail'),

	# Solutions
	url(r'^solutions/(?P<solution_id>\d+)/$', 'solutions.views.solution_detail', name='solution_detail',kwargs={'full' : False}),
    url(r'^solutions/(?P<solution_id>\d+)/full/$', 'solutions.views.solution_detail', name='solution_detail_full', kwargs={'full': True}),
	url(r'^solutions/(?P<solution_id>\d+)/download$', 'solutions.views.solution_download', name='solution_download',kwargs={'full' : False}),
   	url(r'^solutions/(?P<solution_id>\d+)/download/(?P<full>full)/$', 'solutions.views.solution_download', name='solution_download'),
	url(r'^solutions/(?P<solution_id>\d+)/run_checker$', 'solutions.views.solution_run_checker', name='solution_run_checker'),
	url(r'^tasks/(?P<task_id>\d+)/checkerresults/$', 'solutions.views.checker_result_list', name='checker_result_list'),
	url(r'^tasks/(?P<task_id>\d+)/solutiondownload$', 'solutions.views.solution_download_for_task', name='solution_download_for_task',kwargs={'full' : False}),
	url(r'^tasks/(?P<task_id>\d+)/solutiondownload/(?P<full>full)/$', 'solutions.views.solution_download_for_task', name='solution_download_for_task'),
	url(r'^tasks/(?P<task_id>\d+)/solutionupload/$', 'solutions.views.solution_list', name='solution_list'),
	url(r'^tasks/(?P<task_id>\d+)/solutionupload/user/(?P<user_id>\d+)$', 'solutions.views.solution_list', name='solution_list'),
	url(r'^tasks/(?P<task_id>\d+)/solutionupload/test/$', 'solutions.views.test_upload', name='upload_test_solution'),
	url(r'^tasks/(?P<task_id>\d+)/solutionupload/test/student/$', 'solutions.views.test_upload_student', name='upload_test_solution_student'),

	url(r'^tasks/(?P<task_id>\d+)/jplag$', 'solutions.views.jplag', name='solution_jplag'),

	#Attestation
	url(r'^tasks/(?P<task_id>\d+)/attestation/statistics$', 'attestation.views.statistics', name='statistics'),
	url(r'^tasks/(?P<task_id>\d+)/attestation/$', 'attestation.views.attestation_list', name='attestation_list'),
	url(r'^tasks/(?P<task_id>\d+)/attestation/new$', 'attestation.views.new_attestation_for_task', name='new_attestation_for_task'),
	url(r'^solutions/(?P<solution_id>\d+)/attestation/new$', 'attestation.views.new_attestation_for_solution', name='new_attestation_for_solution', kwargs={'force_create' : False}),
	url(r'^solutions/(?P<solution_id>\d+)/attestation/new/(?P<force_create>force_create)$', 'attestation.views.new_attestation_for_solution', name='new_attestation_for_solution'),
	url(r'^attestation/(?P<attestation_id>\d+)/edit$', 'attestation.views.edit_attestation', name='edit_attestation'),
	url(r'^attestation/(?P<attestation_id>\d+)/withdraw$', 'attestation.views.withdraw_attestation', name='withdraw_attestation'),
	url(r'^attestation/(?P<attestation_id>\d+)/run_checker', 'attestation.views.attestation_run_checker', name='attestation_run_checker'),
	url(r'^attestation/(?P<attestation_id>\d+)$', 'attestation.views.view_attestation', name='view_attestation'),
	url(r'^attestation/rating_overview$', 'attestation.views.rating_overview', name='rating_overview'),
	url(r'^attestation/rating_export.csv$', 'attestation.views.rating_export', name='rating_export'),
	
	url(r'^tutorial/$', 'attestation.views.tutorial_overview', name='tutorial_overview'),
   	url(r'^tutorial/(?P<tutorial_id>\d+)$', 'attestation.views.tutorial_overview', name='tutorial_overview'),
	
	# Uploaded media
	url(r'^upload/(?P<path>SolutionArchive/Task_\d+/User_.*/Solution_(?P<solution_id>\d+)/.*)$', 'utilities.views.serve_solution_file'),
	url(r'^upload/(?P<path>TaskMediaFiles.*)$', 'utilities.views.serve_unrestricted'),
	url(r'^upload/(?P<path>jplag.*)$', 'utilities.views.serve_staff_only', name='jplag_download'),
	url(r'^upload/(?P<path>CheckerFiles.*)$', 'utilities.views.serve_staff_only'),
	url(r'^upload/(?P<path>.*)$', 'utilities.views.serve_access_denied'),
	
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

src/attestation/models.py
from django.db import models
from django.conf import settings
from tasks.models import Task
from solutions.models import Solution, SolutionFile
from django.utils.translation import ugettext_lazy as _
from django.core.mail import EmailMessage
from django.template import Context, loader
from django.contrib.sites.requests import RequestSite
from datetime import datetime
from utilities.nub import nub
import difflib

from accounts.models import User
from configuration import get_settings


class Attestation(models.Model):
	""""""

	created = models.DateTimeField(auto_now_add=True)
	solution = models.ForeignKey(Solution)
	author = models.ForeignKey(User, verbose_name="attestation author", limit_choices_to = {'groups__name': 'Tutor'})

	public_comment = models.TextField(blank=True, help_text = _('Comment which is shown to the user.'))
	private_comment = models.TextField(blank=True, help_text = _('Comment which is only visible to tutors'))
	final_grade = models.ForeignKey('RatingScaleItem', null=True, help_text = _('The mark for the whole solution.'))
	
	final = models.BooleanField(default = False, help_text = _('Indicates whether the attestation is ready to be published'))
	published = models.BooleanField(default = False, help_text = _('Indicates whether the user can see the attestation.'))
	published_on = models.DateTimeField(blank=True,null=True,help_text = _('The Date/Time the attestation was published.'))
	
	def publish(self, request, by):
		""" Set attestation to published and send email to user """
		self.published = True
		self.published_on = datetime.now()
		self.save()

                email = self.solution.author.email
                if not email:
                    return

		# Send confirmation email
                t = loader.get_template('attestation/attestation_email.html')
                c = {
                        'attest': self,
                        'protocol': request.is_secure() and "https" or "http",
                        'domain': RequestSite(request).domain,
                        'site_name': settings.SITE_NAME,
                        'by': by,
                        'invisible_attestor' : get_settings().invisible_attestor,
                        }
                subject = _("New attestation for your solution of the task '%s'") % self.solution.task
                body = t.render(Context(c))
                reply_to = ([self.author.email]                    if self.author.email and (not get_settings().invisible_attestor) else []) \
                         + ([get_settings().attestation_reply_to]  if get_settings().attestation_reply_to else [])
                headers = {'Reply-To': ', '.join(reply_to)} if reply_to else None
                email = EmailMessage(subject, body, None, (email,), headers = headers)
                email.send()

        def withdraw(self, request, by):
		self.published = False
                self.final = False
		self.published_on = datetime.now()
		self.save()

                recps = nub([
                    self.solution.author, # student
                    self.author,          # attestation writer
                    by,                   # usually attestation writer, may be trainer
                    ] + list(User.objects.filter(groups__name="Trainer"))  # and, for withdrawals, all trainers
                    )
                emails = [u.email for u in recps if u.email]

                if not emails:
                    return

		# Send confirmation email
                t = loader.get_template('attestation/attestation_withdraw_email.html')
                c = {
                        'attest': self,
                        'protocol': request.is_secure() and "https" or "http",
                        'domain': RequestSite(request).domain,
                        'site_name': settings.SITE_NAME,
                        'by': by,
                        }
                subject = _("Attestation for your solution of the task '%s' withdrawn") % self.solution.task
                body = t.render(Context(c))
                recipients = emails[0:1]
                bcc_recipients = emails[1:]
                email = EmailMessage(subject, body, None, recipients, bcc_recipients)
                email.send()

class AnnotatedSolutionFile(models.Model):
	""""""
	attestation = models.ForeignKey(Attestation)
	solution_file = models.ForeignKey(SolutionFile)
	content = models.TextField(help_text = _('The content of the solution file annotated by the tutor.'), blank = True)
	
	def has_anotations(self):
		original = self.solution_file.content().replace("\r\n","\n").replace("\r","\n")
		anotated = self.content.replace("\r\n","\n").replace("\r","\n")
		return not original == anotated
	
	def content_diff(self):
		d = difflib.Differ()
		original = self.solution_file.content().replace("\r\n","\n").replace("\r","\n").splitlines(0)
		anotated = self.content.replace("\r\n","\n").replace("\r","\n").splitlines(0)
		result = list(d.compare(original, anotated))
		return "\n".join(map(lambda l: l.strip("\n"), result))
	
	def __unicode__(self):
		return self.solution_file.__unicode__()
	
class RatingAspect(models.Model):
	""" describes an review aspect which the reviewer has to evaluate """	
	name = models.CharField(max_length=100, help_text = _('The Name of the Aspect to be rated. E.g.: "Readabylity"'))
	description = models.TextField(help_text = _('Description of the Aspect and how it should be rated. E.w.: "How well is the code structured?"'))
	
	def __unicode__(self):
		return self.name

class RatingScale(models.Model):
	""" describes a scale upone which the reviewer rates the aspect """
	name = models.CharField(max_length=100, help_text = _('The Name of the rating scale for the aspects. E.g.: "School marks"'))
	
	def __unicode__(self):
		return self.name
	
class RatingScaleItem(models.Model):
	""" lists all items(marks) of an rating scale"""	
	scale = models.ForeignKey(RatingScale)
	name = models.CharField(max_length=100, help_text = _('The Name of the item(mark) in the rating scale. E.g.: "A" or "very good" '))
	position = models.PositiveSmallIntegerField(help_text = _('Defines the order in which the items are sorted. Lowest is best.'))
	
	class Meta:
		ordering = ['position']
	
	def __unicode__(self):
		return self.name

class Rating(models.Model):
	""" intermediate model to assign a rating aspect and a rating scale to a task """
	task = models.ForeignKey(Task)
	aspect = models.ForeignKey(RatingAspect)
	scale = models.ForeignKey(RatingScale)
	
	def __unicode__(self):
		return "%s - %s - %s" % (self.task.title, self.aspect.name, self.scale.name)
		
class RatingResult(models.Model):
	""" the rating of particular aspect of a specific solution """
	attestation = models.ForeignKey(Attestation)
	rating = models.ForeignKey(Rating)
	mark = models.ForeignKey(RatingScaleItem, null=True) # allow for db-null so that rating results can be created programaticly without mark (blank = False !)

	def __unicode__(self):
		return unicode(self.rating.aspect) 
	
class Script(models.Model):
	""" save java script function of the rating overview page """
	script = models.TextField(blank=True, help_text = _("This JavaScript will calculate a recommend end note for every user based on final grade of every task."), default="""var sum = 0.0;\nfor (x = 0; x != grades.length; ++x) {\n    grade = parseFloat(grades[x]);\n    if (!isNaN(grade)) {\n        sum += grade;\n    }\n}\nresult=sum;""")
	
	

src/solutions/forms.py
# -*- coding: utf-8 -*-

from django.utils.translation import ugettext_lazy as _
from django.forms.models import ModelForm, inlineformset_factory, BaseInlineFormSet
from django import forms
from django.conf import settings
from utilities.safeuncompressor import SafeUncompressor
import zipfile
import tarfile
import mimetypes
import re

from solutions.models import Solution, SolutionFile
						
ziptype_re = re.compile(r'^application/(zip|x-zip|x-zip-compressed|x-compressed)$')	
tartype_re = re.compile(r'^application/(tar|x-tar|x-tar-compressed)$')	

for (mimetype,extension) in settings.MIMETYPE_ADDITIONAL_EXTENSIONS:
	mimetypes.add_type(mimetype,extension,strict=True)

class SolutionFileForm(ModelForm):
	class Meta:
		model = SolutionFile
		exclude = ('mime_type',)
		
	def clean_file(self):
		data = self.cleaned_data['file']
		task = self.cleaned_data['solution'].task
		max_file_size_kb = task.max_file_size
		max_file_size = 1024 * max_file_size_kb
		supported_types_re = re.compile(task.supported_file_types)
		if data:
			contenttype = mimetypes.guess_type(data.name)[0] # don't rely on the browser: data.content_type could be wrong or empty
			if (contenttype is None) or (not (supported_types_re.match(contenttype) or ziptype_re.match(contenttype) or tartype_re.match(contenttype))):
				raise forms.ValidationError(_('The file of type %s is not supported.' %contenttype))
			if ziptype_re.match(contenttype):
				try:
					zip = zipfile.ZipFile(data)
					if zip.testzip():
						raise forms.ValidationError(_('The zip file seams to be corrupt.'))
					if sum(fileinfo.file_size for fileinfo in zip.infolist()) > 1000000:
						raise forms.ValidationError(_('The zip file is to big.'))	
					for fileinfo in zip.infolist():
						(type, encoding) = mimetypes.guess_type(fileinfo.filename)
						ignorred = SolutionFile.ignorred_file_names_re.search(fileinfo.filename)
						supported = type and supported_types_re.match(type)
						if not ignorred and not supported:
							raise forms.ValidationError(_("The file '%(file)s' of guessed mime type '%(type)s' in this zip file is not supported." %{'file':fileinfo.filename, 'type':type}))
						# check whole zip instead of contained files
						#if fileinfo.file_size > max_file_size:
						#	raise forms.ValidationError(_("The file '%(file)s' is bigger than %(size)iKB which is not suported." %{'file':fileinfo.filename, 'size':max_file_size_kb}))
				except forms.ValidationError:
					raise
				except:
					raise forms.ValidationError(_('Uhoh - something unexpected happened.'))
			elif tartype_re.match(contenttype):
				try:
					uncompressed = SafeUncompressor(data, max_file_size);
					tar = tarfile.open(mode = 'r:', fileobj = uncompressed)
					#if tar.testtar():
					#	raise forms.ValidationError(_('The tar file seams to be corrupt.'))
					if sum(fileinfo.size for fileinfo in tar.getmembers()) > 1000000:
						raise forms.ValidationError(_('The tar file is to big.'))
					for fileinfo in tar.getmembers():
						if not fileinfo.isfile():
							continue
						(type, encoding) = mimetypes.guess_type(fileinfo.name)
						ignorred = SolutionFile.ignorred_file_names_re.search(fileinfo.name)
						supported = type and supported_types_re.match(type)
						if not ignorred and not supported:
							raise forms.ValidationError(_("The file '%(file)s' of guessed mime type '%(type)s' in this tar file is not supported." %{'file':fileinfo.name, 'type':type}))
						# check whole tar instead of contained files
						#if fileinfo.file_size > max_file_size:
						#	raise forms.ValidationError(_("The file '%(file)s' is bigger than %(size)iKB which is not suported." %{'file':fileinfo.name, 'size':max_file_size_kb}))
					data.seek(0)
				except forms.ValidationError:
					raise
				except SafeUncompressor.FileTooLarge:
					raise forms.ValidationError(_('The tar file is to big.'))
 				except:
					raise forms.ValidationError(_('Uhoh - something unexpected happened.'))
			if data.size > max_file_size:
				raise forms.ValidationError(_("The file '%(file)s' is bigger than %(size)iKB which is not suported." %{'file':data.name, 'size':max_file_size_kb}))
			return data

class MyBaseInlineFormSet(BaseInlineFormSet):
    def clean(self):
        super(MyBaseInlineFormSet, self).clean()
        if not reduce(lambda x,y: x + y.changed_data, self.forms, []):
			raise forms.ValidationError(_('You must at least choose one file.'))

SolutionFormSet = inlineformset_factory(Solution, SolutionFile, form=SolutionFileForm, formset=MyBaseInlineFormSet, can_delete=False, extra=3)
ModelSolutionFormSet = inlineformset_factory(Solution, SolutionFile, form=SolutionFileForm, formset=MyBaseInlineFormSet, can_delete=False, extra=1)

src/templates/solutions/checker_result_list.html
{% extends "base.html"%}
{% load i18n %}
{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{{STATIC_URL}}frameworks/jquery.formset/jquery.formset.min.js"></script>
<script type="text/javascript">	
 $(document).ready(function(){
 	$("#help_icon").tooltip({
		position:  "center left"
	});
 })
</script>
<style>
			.verticalText
			{
				text-align: center;
				vertical-align: middle;
				width: 10px;
				margin: 0px;
				padding: 0px;
				padding-left: 3px;
				padding-right: 3px;
				padding-top: 10px;
				white-space: nowrap;
				-webkit-transform: rotate(-90deg); 
				-moz-transform: rotate(-90deg);  				
			};
</style>
{% endblock %}
{% block breadcrumbs %} {{block.super}} > <a href={% url "task_detail" task_id=task.id%}>{{task.title}}</a> > Checker Results{% endblock %}

{% block content %}
		<table>
		<tr>
			<th>Name</th>
			<th>Matriklnr</th>
			<th>Username</th>
			{% for checker in checkers_seen %}
			<th align="center">{{checker}}</th>
			{% endfor %}
		</tr>
		{% for user,results,solution in users_with_checkerresults %}
		<tr>
			<td nowrap><a href={% url "solution_detail_full" solution_id=solution.id %}>{{user}}</a></td>
			<td nowrap>{{user.mat_number}}</td>
			<td nowrap>{{user.username}}</td>
			{% for result in results %}
				{% if result %} 
			<td align="center"><img src="{{STATIC_URL}}admin/img/admin/icon-{{ result.passed|yesno:"yes,no" }}.gif" alt="{{result.passed}}"></td>
				{% else %}
			<td></td>
                	        {% endif %}
			{% endfor %}
		{% endfor %}
	</table>
{% endblock%}

src/templates/solutions/checker_results_inline.html
{% comment %}
	include the folowing depenencies once in the including pages head:
	<script type="text/javascript" src="{{STATIC_URL}}script/solution_inlines.js"></script>
	<link type="text/css" rel="stylesheet" href="{{STATIC_URL}}frameworks/jquery/jquery-ui-theme.css" />
{% endcomment %}


{% for result in results %} 
	<div class="result">
		<h3 class="{{result.only_title|yesno:',clickable'}} result">
			{% if not result.only_title %}<a class="checkerinline" href="#{{result.title}}" title="{{result.title}}" >{% endif %}
			<span class="ui-icon {{result.only_title|yesno:'icon-none,ui-icon-triangle-1-s'}}"></span> 
			{{result.title}} <span class="{{result.public|yesno:',ui-icon ui-icon-locked icon-orange'}}"></span>: 
			<span class="{% if result.passed %} passed {% else %}{% if result.required %} error {% else %} warning {% endif %}{% endif %}">
				{{result.passed|yesno:_("passed, failed")}} {% if result.passed %} {% else %} {% if result.required %} {% else %} (but not required) {% endif %} {% endif %}
			</span>
			<!-- <span class="checkertime">{{ result.runtime }} ms</span> -->
			{% if not result.only_title %}</a>{% endif %}
		</h3>
		<div> <!-- for toggling -->
			<div class="log">
				{{result.log|safe}}
			</div>

			{% if result.artefacts.count %}
				<div class="artefacts">
					<h4>The following artefacts were produced:</h4>
					<ul>
						{% for artefact in result.artefacts.all %}
							<li>
							  <a href="{{ artefact.file.url }}?view" title="View">{{ artefact }}</a>
							  <a href="{{ artefact.file.url }}" title="Download"><span class="ui-icon icon-red ui-icon-disk" title="Download all solutions, including checker files"></span></a>
							</li>
						{% endfor %}
					</ul>
				</div>
			{% endif %}
		</div>
	</div>
{%endfor%}

src/templates/solutions/jplag.html
{% extends "base.html" %}
{% load i18n  %}
{% block breadcrumbs %}
{{block.super}}
&gt; <a href={% url "task_detail" task_id=task.id%}>{{task.title}}</a>
&gt; jPlag output
{% endblock %}
{% block content %}
<div id='jplag'>

{% if HAS_JPLAG %}
 <h1>{{task.title}} – jPlag results</h1>

 <form method="POST">

 {% csrf_token %}
 {% if task.did_jplag_run %}
   <a href="{% url "jplag_download" path=task.jplag_log_url %}">jPlag log file</a>
   &bull;
 {% endif %}

 {% if task.did_jplag_succeed %}
     <a href="{% url "jplag_download" path=task.jplag_index_url %}" target="_blank">Open jPlag output in new window</a> &bull;
 {% endif %}

 <select name="lang">
   {% for opt in task.jplag_languages.keys %}
	<option value="{{ opt }}" {% if opt = jplag_lang %} selected="selected" {% endif %}>{{opt}}</option>
   {% endfor %}
 </select>

 {% if task.did_jplag_run %}
   <input type="submit" value="Re-run jPlag"/>
 {% else %}
   <input type="submit" value="Run jPlag"/>
 {% endif %}

 {% if not task.jplag_up_to_date %}
   &bull; <span class="warning">Warning: jPlag output not up-to-date with regard to final solutions.</span>
 {% endif %}

 {% if task.did_jplag_run %}
   {% if task.did_jplag_succeed %}
     <br/><iframe width="100%" height="800" src="{% url "jplag_download" path=task.jplag_index_url %}"></iframe>
   {% else %}
     &bull; <span class="warning">Warning: The last jPlag run did not produce any output.</span>
   {% endif %}
 {% else %}
   <p>
   jPlag has not yet run.
   </p>
   <p>
   <input type="submit" value="Run jPlag"/>
   </p>
 {% endif %}
 </form>

{% else %}

This Praktomat instance has no integrated jPlag support. Please download the jPlag jar file and configure the <code>JPLAGJAR</code> setting.

{% endif %}

</div>{% endblock %}

src/templates/solutions/solution_detail.html
{% extends "base.html" %}
{% load i18n  %}
{% block extrahead %}{{ block.super }}
	<script type="text/javascript" src="{{STATIC_URL}}script/solution_inlines.js"></script>
	<link type="text/css" rel="stylesheet" href="{{STATIC_URL}}styles/pygments_friendly.css" />
{% endblock %}
{% block breadcrumbs %}
{{block.super}}
&gt; <a href={% url "task_detail" task_id=solution.task.id%}>{{solution.task.title}}</a>
&gt; {% if user.is_tutor or user.is_trainer %} <a href={% url "attestation_list" solution.task.id %}>My attestations</a>
&gt; <a href={% url "solution_list" task_id=solution.task.id user_id=solution.author.id %}>{{solution.author}}'s solutions</a>{% else %}<a href={% url "solution_list" task_id=solution.task.id%}>My solutions</a>{% endif %}
&gt; Solution {{solution.number}}
{% endblock %}
{% block content %}<div id='solution_detail'>

<h1>{{solution.task.title}}</h1>
{% if user.is_tutor or user.is_trainer %}{% if not full %}
   <p>
	(as seen by {{solution.author}},
	<a href="{% url "solution_detail_full" solution_id=solution.id %}">also show non-public checker results</a>)
   </p>
{% endif %}{% endif %}

{% if solution.accepted %}
	{% if solution.warnings %}
		<p class="warning" id='commit_text'>{% trans "All required tests have been passed. Nevertheless there is at least one warning" %} 
		{% if not solution.task.expired %}{% trans "You should consider correcting it." %}{% endif %}</p>
	{% else %}
		<p class="passed" id='commit_text'>{% trans "All required tests have been passed." %}</p>
	{% endif %}
{% else %}
	<p class="error" id='commit_text'>{% trans "Not all required tests have been passed." %}
	{% if not solution.task.expired %}{% trans "Please correct the errors below and try again!" %}{% endif %}</p>
{% endif %}

<p>
	{% if solution.testupload %}
		This is a test submission, and otherwise ignored.
	{% endif %}
	{% if solution.final %}
		This is your current final solution.
	{% else %}
		 This is NOT your current final solution.
	{% endif %}
</p>

{% if solution.plagiarism and attestationsPublished %}
	<p class='error'><span class="icon ui-icon-alert icon-red"></span>{% trans "Marked as Plagiarism" %}</p>
{% endif %}

{% if not solution.final and not solution.testupload and not solution.task.expired %}
    {% if accept_all_solutions or solution.accepted %}
        <form method="post">{% csrf_token %}
            <input type="submit" value="Resubmit" />
            <p class="help">You can resubmit this solution to make this your final solution.</p>
        </form>
    {% endif %}
{% endif %}

{% if full %}
{% with solution.allCheckerResults as results %}
	{% if results %}
		<h2>{% trans "Results" %}</h2>
		{% include "solutions/checker_results_inline.html" %}
	{% endif %}
{% endwith %}
{% else %}
{% with solution.publicCheckerResults as results %}
	{% if results %}
		<h2>{% trans "Results" %}</h2>
		{% include "solutions/checker_results_inline.html" %}
	{% endif %}
{% endwith %}
{% endif %}

<h2>{% trans "Files" %}</h2>
{% with solution.solutionfile_set.all as solutionfiles %}
	{% include "solutions/solution_files_inline.html" %}
{% endwith %}

</div>{% endblock %}

src/templates/solutions/solution_list_inline.html
<div class='solution'>
	{% spaceless %} 
		{% if solution.accepted%}
			{% if solution.warnings%}
				<span class="icon ui-icon-bullet icon-orange" title='Warnings'></span>
			{% else %}
				<span class="icon ui-icon-bullet icon-green" title='No Warnings'></span>
			{% endif %}
		{% else %}
			<span class="icon ui-icon-bullet icon-red" title='Errors'></span>
		{% endif %}
		<a href="{% url "solution_detail" solution_id=solution.id %}">
			Solution {{solution.number}}
		</a>
		<span> ({{solution.creation_date|timesince}} ago{% if solution.testupload %}, test submission{% endif %})</span>
		<br/>
	{% endspaceless %}
</div>

{% if solution.plagiarism and attestationsPublished %}
	<div class='attestation'>
		<span class='plagiarism error'><span class="icon ui-icon-alert icon-red"></span>Marked as Plagiarism</span>
	</div>
{% else %}
	{% for attest in solution.attestation_set.all %}
		<div class='attestation'>
			{% if attest.published %}
				<span class="icon ui-icon-script" title='Attest'></span><a href={% url "view_attestation" attestation_id=attest.id%}>Attestation</a> {% if not invisible_attestor %}by {{attest.author.get_full_name}}{% endif %}<br/>
			{% endif %}
		</div>
	{%endfor%}
{% endif %}